-- CREATE TABLE `questions` (
--   `question_id` int(11) NOT NULL,
--   `lesson_id` int(11) NOT NULL,
--   `type` int(11) NOT NULL,
--   `question` text NOT NULL,
--   `option1` text DEFAULT NULL,
--   `option2` text DEFAULT NULL,
--   `option3` text DEFAULT NULL,
--   `option4` text DEFAULT NULL,
--   `option5` text DEFAULT NULL,
--   `feedback1` text DEFAULT NULL,
--   `feedback2` text DEFAULT NULL,
--   `feedback3` text DEFAULT NULL,
--   `feedback4` text DEFAULT NULL,
--   `feedback5` text DEFAULT NULL,
--   `answer` text NOT NULL,
--   `marks` double NOT NULL,
--   `createdate` timestamp NOT NULL DEFAULT current_timestamp()
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --
-- Dumping data for table `questions`
--

INSERT INTO `questions` (`question_id`, `lesson_id`, `type`, `question`, `option1`, `option2`, `option3`, `option4`, `option5`, `feedback1`, `feedback2`, `feedback3`, `feedback4`, `feedback5`, `answer`, `marks`, `createdate`) VALUES
(1, 13, 1, 'What is social studies about?', 'Playing games', 'Studying the environment', 'How people interact with their environment', 'Cooking food', NULL, 'Incorrect. Social studies is not focused on games.', 'Incorrect. While the environment is important, social studies focuses on how people interact with it.', 'Correct. Social studies is about studying the relationship between people and their surroundings.', 'Incorrect. Cooking food is not part of social studies.', NULL, '3', 0, '2025-04-08 16:37:57'),
(2, 13, 1, 'Who was walking with Folake when she went to the library?', 'Her teacher, Mrs. Adeola', 'Her friend, Bolu', 'Her cousin, Adebayo', 'Her neighbor, Mama Titi', NULL, 'Correct. Mrs. Adeola was walking with Folake to the library.', 'Incorrect. Folake was not walking with her friend Bolu, but with her teacher.', 'Incorrect. Adebayo is not mentioned in the text as walking with Folake.', 'Incorrect. Mama Titi is not mentioned as accompanying Folake.', NULL, '1', 0, '2025-04-08 16:37:57'),
(3, 13, 1, 'What did Mrs. Adeola explain social studies helps us understand?', 'The weather', 'How to grow food', 'The connection between people and the environment', 'How to play games', NULL, 'Incorrect. Weather is not the primary focus of social studies.', 'Incorrect. While growing food is a part of community life, social studies focuses on interactions between people and their environment.', 'Correct. Social studies helps understand how people relate to and affect their environment.', 'Incorrect. Social studies is not about playing games.', NULL, '3', 0, '2025-04-08 16:37:57'),
(4, 13, 1, 'What did Folake feel after leaving the library?', 'Sad', 'Hungry', 'Excited', 'Tired', NULL, 'Incorrect. There is no mention of Folake feeling sad.', 'Incorrect. The text does not mention Folake feeling hungry.', 'Correct. Folake felt excited after learning about social studies.', 'Incorrect. Tiredness is not mentioned in the text.', NULL, '3', 0, '2025-04-08 16:37:57'),
(5, 13, 1, 'Which of these is an example of how people interact with their environment?', 'Helping each other', 'Playing games', 'Ignoring the environment', 'Sleeping', NULL, 'Correct. Helping each other is one way that people interact positively with their environment.', 'Incorrect. Playing games does not directly involve interaction with the environment.', 'Incorrect. Ignoring the environment is not a positive or constructive interaction.', 'Incorrect. Sleeping is a personal activity that does not involve interacting with the environment.', NULL, '1', 0, '2025-04-08 16:37:57'),
(6, 13, 1, 'What is social studies mainly about?', 'Learning math', 'Understanding people’s interactions with the environment', 'Learning how to paint', 'Playing outside', NULL, 'Incorrect. Math is not the focus of social studies.', 'Correct. Social studies is about studying how people interact with their surroundings.', 'Incorrect. Social studies is not focused on arts and painting.', 'Incorrect. Social studies goes beyond recreational activities.', NULL, '2', 0, '2025-04-08 16:37:57'),
(7, 13, 1, 'How did Mrs. Adeola explain social studies?', 'It’s about building houses', 'It’s about people working together to solve problems', 'It’s about telling stories', 'It’s about playing sports', NULL, 'Incorrect. Building houses is part of community life but not the main focus of social studies.', 'Correct. Social studies explores how people collaborate to address issues.', 'Incorrect. While stories are important in learning, social studies is more about understanding social interactions.', 'Incorrect. Sports is not a focus of social studies.', NULL, '2', 0, '2025-04-08 16:37:57'),
(8, 13, 1, 'What did Folake imagine when learning about social studies?', 'People in a different country', 'Diverse landscapes and cultures across Nigeria', 'A magic kingdom', 'Animals in the jungle', NULL, 'Incorrect. Folake thought about Nigeria specifically.', 'Correct. Folake imagined different parts of Nigeria, reflecting the diversity discussed in the chapter.', 'Incorrect. There’s no mention of a magic kingdom in the text.', 'Incorrect. The focus was on people and their environments, not animals.', NULL, '2', 0, '2025-04-08 16:37:57'),
(9, 13, 2, 'How would you help protect the environment in your community?', 'By ignoring it', 'By planting trees and picking up trash', 'By using too much water', 'By throwing waste on the ground', NULL, 'Incorrect. Ignoring the environment does not help protect it.', 'Correct. Planting trees and cleaning up trash are actions that help protect the environment.', 'Incorrect. Using too much water harms the environment.', 'Incorrect. Throwing waste worsens environmental problems.', NULL, '2', 0, '2025-04-08 16:37:57'),
(10, 13, 2, 'If you saw someone throwing trash on the ground, what would you do?', 'Throw more trash', 'Ignore them', 'Tell them to pick it up and explain the importance of keeping the environment clean', 'Shout at them', NULL, 'Incorrect. Throwing more trash makes the problem worse.', 'Incorrect. Ignoring the issue does not solve it.', 'Correct. Educating others about the environment is a responsible action.', 'Incorrect. Shouting is not a helpful way to address the issue.', NULL, '3', 0, '2025-04-08 16:37:57'),
(11, 13, 2, 'What would happen if people did not work together in their community?', 'They would build more houses', 'They would solve problems alone', 'They would face many problems like hunger and pollution', 'They would travel to other places', NULL, 'Incorrect. Not working together would not lead to progress.', 'Incorrect. Solving problems alone is harder, and community collaboration is essential.', 'Correct. Without teamwork, communities would struggle with issues like hunger and pollution.', 'Incorrect. Moving to other places doesn’t solve the problem.', NULL, '3', 0, '2025-04-08 16:37:57'),
(12, 13, 2, 'What would you do if you saw someone cleaning the environment in your community?', 'Ignore them', 'Help them clean and encourage others to join', 'Laugh at them', 'Tell them to stop', NULL, 'Incorrect. Ignoring a helpful action is not supportive.', 'Correct. Helping and encouraging others to participate supports the environment.', 'Incorrect. Laughing at others’ good actions is disrespectful.', 'Incorrect. Telling them to stop is counterproductive.', NULL, '2', 0, '2025-04-08 16:37:57'),
(13, 13, 2, 'If you were designing a project to help your community, what would you focus on?', 'Making more toys', 'Helping people work together to protect their environment', 'Building a playground for only kids', 'Telling stories', NULL, 'Incorrect. While toys are fun, the project would focus on community issues.', 'Correct. The project would aim to protect the environment, a community concern.', 'Incorrect. A playground is important, but the focus would be on broader community needs.', 'Incorrect. Telling stories alone doesn’t solve environmental issues.', NULL, '2', 0, '2025-04-08 16:37:57'),
(14, 13, 2, 'How can communities help each other solve problems?', 'By staying quiet', 'By ignoring the problems', 'By working together and sharing ideas', 'By letting others take care of it', NULL, 'Incorrect. Silence does not solve problems.', 'Incorrect. Ignoring problems worsens them.', 'Correct. Collaboration is key to solving community problems.', 'Incorrect. Community problems require collective effort.', NULL, '3', 0, '2025-04-08 16:37:57'),
(15, 13, 2, 'What can you do to make sure everyone in your community has enough to eat?', 'Ignore them', 'Help build a food-sharing program', 'Only care about yourself', 'Ask others to help only if they want', NULL, 'Incorrect. Ignoring people’s needs doesn’t help.', 'Correct. A food-sharing program can ensure that everyone has enough food.', 'Incorrect. Selfishness doesn’t address community needs.', 'Incorrect. It’s important to encourage everyone to participate.', NULL, '2', 0, '2025-04-08 16:37:57'),
(16, 13, 2, 'Which of these would be a good solution to protect the environment in your community?', 'Ignoring the environment', 'Planting more trees and reducing pollution', 'Throwing more trash on the streets', 'Using plastic everywhere', NULL, 'Incorrect. Ignoring the environment worsens problems like pollution and deforestation.', 'Correct. Planting trees helps clean the air, and reducing pollution protects the environment.', 'Incorrect. Throwing trash creates more pollution and harms the environment.', 'Incorrect. Overuse of plastic contributes to pollution and environmental damage.', NULL, '2', 0, '2025-04-08 16:37:57'),
(17, 13, 3, 'What do you think is the best way for a community to stay clean?', 'By having people pick up litter together', 'By leaving trash everywhere', 'By keeping all the windows shut', 'By not caring about the environment', NULL, 'Correct. Working together to clean up keeps the community tidy and encourages responsibility.', 'Incorrect. Leaving trash causes pollution and health problems.', 'Incorrect. Closing windows does not impact cleanliness; it’s about actions like cleaning.', 'Incorrect. Not caring about the environment leads to a messy and unhealthy community.', NULL, '1', 0, '2025-04-08 16:37:57'),
(18, 13, 3, 'How can people in your community work together to help each other?', 'By sharing food and supporting one another', 'By ignoring each other', 'By arguing all the time', 'By staying at home', NULL, 'Correct. Helping each other builds strong relationships and a caring community.', 'Incorrect. Ignoring each other leads to division and weakens community bonds.', 'Incorrect. Constant arguing causes conflict and hurts cooperation.', 'Incorrect. Staying isolated limits ways to help others and work together.', NULL, '1', 0, '2025-04-08 16:37:57'),
(19, 13, 3, 'What would you do if there was a lot of pollution in your community?', 'Ignore it', 'Start a clean-up campaign and encourage everyone to help', 'Throw more garbage', 'Make a mess on purpose', NULL, 'Incorrect. Ignoring pollution makes the problem worse.', 'Correct. A clean-up campaign involves the community and reduces pollution.', 'Incorrect. Adding more trash worsens pollution.', 'Incorrect. Deliberately making a mess causes more harm and problems.', NULL, '2', 0, '2025-04-08 16:37:57'),
(20, 13, 3, 'If you were the leader of your community, what is the first thing you would do to protect the environment?', 'Start an environmental education program', 'Ignore the community’s needs', 'Build more houses', 'Make more toys for kids', NULL, 'Correct. Teaching people about the environment helps them understand the importance of protecting it.', 'Incorrect. Ignoring the needs of the community worsens problems and affects everyone.', 'Incorrect. Building more houses without planning can harm the environment.', 'Incorrect. While toys are fun, they do not directly help protect the environment.', NULL, '1', 0, '2025-04-08 16:37:57'),
(21, 13, 3, 'Imagine you could create a new way for people to solve environmental problems. What would you do?', 'Ask people to stop working together', 'Create a program to recycle and reuse materials', 'Tell everyone to ignore the environment', 'Encourage people to waste more resources', NULL, 'Incorrect. Stopping cooperation would prevent solving problems.', 'Correct. Recycling helps reduce waste and conserve resources.', 'Incorrect. Ignoring environmental issues makes the problems worse.', 'Incorrect. Wasting resources harms the environment and leads to future problems.', NULL, '2', 0, '2025-04-08 16:37:57'),
(43, 14, 1, 'What does respect mean?', 'Liking someone for doing good things', 'Being scared of someone', 'Not talking to people', 'Laughing at people', NULL, '✅ Yes!\n💡 Think of how Zara felt about the people who worked hard and helped others.', '❌ No, that\'s not respect.\n💡 Respect is about liking someone, not being afraid.', '❌ That\'s not it.\n💡 Zara talked kindly to others. She didn\'t ignore them.', '❌ That\'s unkind.\n💡 Would Zara ever do that to someone she respects?', NULL, '1', 0, '2025-04-09 10:14:09'),
(44, 14, 1, 'Who is Chief Okonkwo?', 'Zara\'s brother', 'The man who sells books', 'A wise traditional ruler', 'Zara\'s teacher', NULL, '❌ Nope.\n💡 Think about someone in the village who leads people.', '❌ Not quite.\n💡 He\'s not from the library.', '✅ That\'s right!\n💡 He helps the people in the village and is respected.', '❌ That\'s someone else.\n💡 Teachers are important, but Chief Okonkwo is a village leader.', NULL, '3', 0, '2025-04-09 10:14:09'),
(45, 14, 1, 'Why does Zara respect her parents?', 'Because they are strict', 'Because they are famous', 'Because they travel a lot', 'Because they work hard for the family', NULL, '❌ No, that\'s not why.\n💡 She respects their care, not their rules.', '❌ Nope.\n💡 It\'s not about being known by many people.', '❌ That wasn\'t in the story.\n💡 Look for what they do, not where they go.', '✅ Yes!\n💡 Zara admires how they help and care for her.', NULL, '4', 0, '2025-04-09 10:14:09'),
(46, 14, 1, 'How did Zara show respect to elders?', 'She ran away from them', 'She smiled and greeted them', 'She shouted at them', 'She did not look at them', NULL, '❌ That\'s not kind.\n💡 Zara didn\'t hide from elders — she was friendly.', '✅ That\'s right!\n💡 A smile and greeting show good manners.', '❌ Oh no! That\'s rude.\n💡 Zara used kind words.', '❌ That\'s not respectful.\n💡 Think about how you treat someone you like.', NULL, '2', 0, '2025-04-09 10:14:09'),
(47, 14, 1, 'What is a community?', 'A big school', 'A group of animals', 'People who live together in the same place', 'A toy box', NULL, '❌ Not exactly.\n💡 A school can be part of a community, but not all of it.', '❌ That\'s different.\n💡 The story talks about people, not animals.', '✅ Yes!\n💡 Think of Zara\'s village with people helping each other.', '❌ That\'s not it.\n💡 Communities are made of people, not things.', NULL, '3', 0, '2025-04-09 10:14:09'),
(48, 14, 1, 'What does it mean to be punctual?', 'To sleep late', 'To miss school', 'To come late', 'To be on time', NULL, '❌ Not quite.\n💡 That might make you late, not on time.', '❌ Nope.\n💡 Being punctual means you arrive when you\'re supposed to.', '❌ That\'s the opposite.\n💡 Zara tried to be early, not late.', '✅ Yes!\n💡 Zara respected time by not being late.', NULL, '4', 0, '2025-04-09 10:14:09'),
(49, 14, 1, 'What does the national flag stand for?', 'It is a symbol of the country', 'It is a favorite toy', 'It is a school book', 'It is a kind of food', NULL, '✅ You got it!\n💡 A flag helps us know and love our nation.', '❌ That\'s not right.\n💡 Think of something that shows pride in your country.', '❌ No.\n💡 Books are for learning — a flag is something we see.', '❌ Not even close.\n💡 We don\'t eat a flag, we respect it.', NULL, '1', 0, '2025-04-09 10:14:09'),
(50, 14, 1, 'Which of these shows respect for public things?', 'Writing on walls', 'Keeping the library clean', 'Throwing trash on the playground', 'Breaking chairs', NULL, '❌ That\'s bad behavior.\n💡 Think of how to care for shared places.', '✅ That\'s it!\n💡 Zara loved public places and kept them tidy.', '❌ That\'s not nice.\n💡 Think of what helps everyone enjoy the space.', '❌ Nope.\n💡 Respect means helping, not hurting.', NULL, '2', 0, '2025-04-09 10:14:09'),
(51, 14, 2, 'Zara sees someone dropping trash on the ground. What should she do to show respect for the environment?', 'Ignore them and walk away', 'Yell at them', 'Kindly ask them to use the bin', 'Drop trash too', NULL, '❌ Not helpful.\n💡 Respect means caring for your community.', '❌ That\'s rude.\n💡 Zara always speaks kindly, even when helping others.', '✅ Yes!\n💡 Helping someone in a nice way is respectful.', '❌ That makes things worse.\n💡 Zara wants to keep the village clean.', NULL, '3', 0, '2025-04-09 10:14:09'),
(52, 14, 2, 'Zara wants to show respect for time. What should she do?', 'Sleep until late morning', 'Play outside during school', 'Wait for someone to call her many times', 'Get ready early for school', NULL, '❌ That\'s not punctual.\n💡 Being on time means waking up early.', '❌ Nope.\n💡 Time for learning is different from playtime.', '❌ That wastes time.\n💡 Zara should be ready on her own.', '✅ Exactly!\n💡 Being punctual shows you care about others\' time too.', NULL, '4', 0, '2025-04-09 10:14:09'),
(53, 14, 2, 'Zara is at the playground. What shows she respects public places?', 'Pushes others off the swing', 'Waits her turn on the swing', 'Takes the swing home', 'Writes her name on the slide', NULL, '❌ That\'s not fair.\n💡 Respect means thinking about others, not just yourself.', '✅ Well done!\n💡 Zara is patient and fair.', '❌ Oh no!\n💡 Public things are for everyone, not just one person.', '❌ That\'s damage.\n💡 Respect means keeping things nice for others.', NULL, '2', 0, '2025-04-09 10:14:09'),
(54, 14, 2, 'Which action helps Zara build a peaceful community?', 'Helping a neighbor carry water', 'Fighting with her friends', 'Shouting during assembly', 'Tearing books in the library', NULL, '✅ Yes!\n💡 Helping each other brings people closer.', '❌ That breaks peace.\n💡 Respect means solving problems kindly.', '❌ That\'s not polite.\n💡 Zara shows respect by being calm.', '❌ Not at all.\n💡 A peaceful community needs care.', NULL, '1', 0, '2025-04-09 10:14:09'),
(55, 14, 2, 'Why do people stand quietly during the national anthem?', 'Because they are sleepy', 'Because it\'s a fun game', 'Because the teacher said so', 'To show respect for their country', NULL, '❌ Not really.\n💡 They stand proud, not tired.', '❌ No, it\'s serious.\n💡 The anthem is not for playtime.', '❌ That\'s not the main reason.\n💡 Think of what the anthem means.', '✅ Correct!\n💡 It\'s a way to honor your nation — it\'s a symbol.', NULL, '4', 0, '2025-04-09 10:14:09'),
(56, 14, 2, 'How are greeting elders and cleaning the playground alike?', 'They are both fun', 'They are both loud', 'They both show respect', 'They both take a long time', NULL, '❌ Not always fun.\n💡 Think of the meaning behind them.', '❌ Zara is polite, not noisy.', '✅ Yes!\n💡 One is for people, one is for places — both show care.', '❌ Not really.\n💡 It\'s not about time — it\'s about meaning.', NULL, '3', 0, '2025-04-09 10:14:09'),
(57, 14, 2, 'What might happen if no one respects public property?', 'Everyone gets rich', 'The community becomes dirty and broken', 'Zara will be happy', 'Everyone claps and sings', NULL, '❌ That doesn\'t make sense.\n💡 Think of what happens when things are not cared for.', '✅ Yes!\n💡 Without respect, things fall apart.', '❌ No way.\n💡 Zara wants her village clean and safe.', '❌ That\'s not related.\n💡 Clapping doesn\'t fix broken places.', NULL, '2', 0, '2025-04-09 10:14:09'),
(58, 14, 2, 'What is one difference between respecting people and things?', 'People have feelings, things do not', 'Things are more important', 'You don\'t need to care for people', 'You can throw people away', NULL, '✅ Correct!\n💡 That\'s why we are extra kind to people.', '❌ Not true.\n💡 People matter most.', '❌ Oh no!\n💡 Zara cares deeply about others.', '❌ That\'s hurtful and wrong.\n💡 Zara would never do that.', NULL, '1', 0, '2025-04-09 10:14:09'),
(59, 14, 3, 'Zara sees her friend not greeting an elder. What should she do to show leadership and respect?', 'Laugh at her friend', 'Ignore the elder too', 'Gently remind her friend to greet the elder', 'Tell the elder she\'s rude', NULL, '❌ That\'s not kind.\n💡 Laughing can hurt feelings.', '❌ Nope.\n💡 Zara should do what\'s right even when others don\'t.', '✅ Yes!\n💡 Helping others do the right thing is respectful.', '❌ That\'s disrespectful.\n💡 Speak kindly, even when correcting.', NULL, '3', 0, '2025-04-09 10:14:09'),
(60, 14, 3, 'Zara wants to make a Respect Poster for her class. Which idea is BEST to put on the poster?', 'Shout First, Think Later!', 'Speak Kindly. Listen Carefully. Care for Others.', 'Take Everything You Want!', 'Only Respect Your Best Friends', NULL, '❌ That\'s not respectful.\n💡 Zara uses calm, kind words.', '✅ Perfect!\n💡 All of these are ways to show respect.', '❌ That\'s selfish.\n💡 Respect means thinking of others too.', '❌ That\'s not fair.\n💡 Everyone deserves respect, not just friends.', NULL, '2', 0, '2025-04-09 10:14:09'),
(61, 14, 3, 'Zara wants to teach her little brother about respect. What is the BEST way to do that?', 'Shout at him when he forgets', 'Tell him respect is boring', 'Let him do whatever he wants', 'Show him how to greet elders and take care of toys', NULL, '❌ That\'s not the best way to teach.\n💡 Zara uses gentle ways to guide others.', '❌ That won\'t help.\n💡 Zara finds respect exciting and fun.', '❌ That doesn\'t teach anything.\n💡 Kids need help to learn what\'s right.', '✅ Yes!\n💡 Showing by example is a smart way to teach.', NULL, '4', 0, '2025-04-09 10:14:09'),
(62, 14, 3, 'Zara\'s class wants to write a class rule about respect. Which rule is the most helpful?', 'Always listen when someone is talking', 'Only play with your best friend', 'Don\'t clean the classroom', 'Laugh when someone makes a mistake', NULL, '✅ That\'s a kind and respectful rule!\n💡 Listening shows you care.', '❌ That leaves people out.\n💡 Respect includes everyone.', '❌ That\'s not helpful.\n💡 Respect means caring for your space.', '❌ That can hurt someone\'s feelings.\n💡 Zara is gentle with others.', NULL, '1', 0, '2025-04-09 10:14:09'),
(63, 14, 3, 'Imagine your school wants to become more respectful. What is one new idea you can share to help?', 'Give rewards only to the quietest students', 'Shout \"RESPECT!\" every hour', 'Make a \"Respect Tree\" where everyone adds kind actions on leaves', 'Let students choose to follow rules or not', NULL, '❌ Not fair.\n💡 Everyone shows respect in different ways.', '❌ That might be fun, but not helpful.\n💡 Actions speak louder than words.', '✅ Creative and kind!\n💡 A fun way to show and grow respect together.', '❌ That can lead to trouble.\n💡 Respect needs good choices every day.', NULL, '3', 0, '2025-04-09 10:14:09'),
(64, 15, 1, 'What does respect mean?', 'Liking someone for doing good things', 'Being scared of someone', 'Not talking to people', 'Laughing at people', NULL, '✅ Yes! Think of how Zara felt about the people who worked hard and helped others.', '❌ No, that\'s not respect. Respect is about liking someone, not being afraid.', '❌ That\'s not it. Zara talked kindly to others. She didn\'t ignore them.', '❌ That\'s unkind. Would Zara ever do that to someone she respects?', NULL, '1', 0, '2025-04-09 10:28:41'),
(65, 15, 1, 'Who is Chief Okonkwo?', 'Zara\'s brother', 'The man who sells books', 'A wise traditional ruler', 'Zara\'s teacher', NULL, '❌ Nope. Think about someone in the village who leads people.', '❌ Not quite. He\'s not from the library.', '✅ That\'s right! He helps the people in the village and is respected.', '❌ That\'s someone else. Teachers are important, but Chief Okonkwo is a village leader.', NULL, '3', 0, '2025-04-09 10:28:41'),
(66, 15, 1, 'Why does Zara respect her parents?', 'Because they are strict', 'Because they are famous', 'Because they travel a lot', 'Because they work hard for the family', NULL, '❌ No, that\'s not why. She respects their care, not their rules.', '❌ Nope. It\'s not about being known by many people.', '❌ That wasn\'t in the story. Look for what they do, not where they go.', '✅ Yes! Zara admires how they help and care for her.', NULL, '4', 0, '2025-04-09 10:28:41'),
(67, 15, 1, 'How did Zara show respect to elders?', 'She ran away from them', 'She smiled and greeted them', 'She shouted at them', 'She did not look at them', NULL, '❌ That\'s not kind. Zara didn\'t hide from elders — she was friendly.', '✅ That\'s right! A smile and greeting show good manners.', '❌ Oh no! That\'s rude. Zara used kind words.', '❌ That\'s not respectful. Think about how you treat someone you like.', NULL, '2', 0, '2025-04-09 10:28:41'),
(68, 15, 1, 'What is a community?', 'A big school', 'A group of animals', 'People who live together in the same place', 'A toy box', NULL, '❌ Not exactly. A school can be part of a community, but not all of it.', '❌ That\'s different. The story talks about people, not animals.', '✅ Yes! Think of Zara\'s village with people helping each other.', '❌ That\'s not it. Communities are made of people, not things.', NULL, '3', 0, '2025-04-09 10:28:41'),
(69, 15, 1, 'What does it mean to be punctual?', 'To sleep late', 'To miss school', 'To come late', 'To be on time', NULL, '❌ Not quite. That might make you late, not on time.', '❌ Nope. Being punctual means you arrive when you\'re supposed to.', '❌ That\'s the opposite. Zara tried to be early, not late.', '✅ Yes! Zara respected time by not being late.', NULL, '4', 0, '2025-04-09 10:28:41'),
(70, 15, 1, 'What does the national flag stand for?', 'It is a symbol of the country', 'It is a favorite toy', 'It is a school book', 'It is a kind of food', NULL, '✅ You got it! A flag helps us know and love our nation.', '❌ That\'s not right. Think of something that shows pride in your country.', '❌ No. Books are for learning — a flag is something we see.', '❌ Not even close. We don\'t eat a flag, we respect it.', NULL, '1', 0, '2025-04-09 10:28:41'),
(71, 15, 1, 'Which of these shows respect for public things?', 'Writing on walls', 'Keeping the library clean', 'Throwing trash on the playground', 'Breaking chairs', NULL, '❌ That\'s bad behavior. Think of how to care for shared places.', '✅ That\'s it! Zara loved public places and kept them tidy.', '❌ That\'s not nice. Think of what helps everyone enjoy the space.', '❌ Nope. Respect means helping, not hurting.', NULL, '2', 0, '2025-04-09 10:28:41'),
(72, 15, 2, 'Zara sees someone dropping trash on the ground. What should she do to show respect for the environment?', 'Ignore them and walk away', 'Yell at them', 'Kindly ask them to use the bin', 'Drop trash too', NULL, '❌ Not helpful. Respect means caring for your community.', '❌ That\'s rude. Zara always speaks kindly, even when helping others.', '✅ Yes! Helping someone in a nice way is respectful.', '❌ That makes things worse. Zara wants to keep the village clean.', NULL, '3', 0, '2025-04-09 10:28:41'),
(73, 15, 2, 'Zara wants to show respect for time. What should she do?', 'Sleep until late morning', 'Play outside during school', 'Wait for someone to call her many times', 'Get ready early for school', NULL, '❌ That\'s not punctual. Being on time means waking up early.', '❌ Nope. Time for learning is different from playtime.', '❌ That wastes time. Zara should be ready on her own.', '✅ Exactly! Being punctual shows you care about others\' time too.', NULL, '4', 0, '2025-04-09 10:28:41'),
(74, 15, 2, 'Zara is at the playground. What shows she respects public places?', 'Pushes others off the swing', 'Waits her turn on the swing', 'Takes the swing home', 'Writes her name on the slide', NULL, '❌ That\'s not fair. Respect means thinking about others, not just yourself.', '✅ Well done! Zara is patient and fair.', '❌ Oh no! Public things are for everyone, not just one person.', '❌ That\'s damage. Respect means keeping things nice for others.', NULL, '2', 0, '2025-04-09 10:28:41'),
(75, 15, 2, 'Which action helps Zara build a peaceful community?', 'Helping a neighbor carry water', 'Fighting with her friends', 'Shouting during assembly', 'Tearing books in the library', NULL, '✅ Yes! Helping each other brings people closer.', '❌ That breaks peace. Respect means solving problems kindly.', '❌ That\'s not polite. Zara shows respect by being calm.', '❌ Not at all. A peaceful community needs care.', NULL, '1', 0, '2025-04-09 10:28:41'),
(76, 15, 2, 'Why do people stand quietly during the national anthem?', 'Because they are sleepy', 'Because it\'s a fun game', 'Because the teacher said so', 'To show respect for their country', NULL, '❌ Not really. They stand proud, not tired.', '❌ No, it\'s serious. The anthem is not for playtime.', '❌ That\'s not the main reason. Think of what the anthem means.', '✅ Correct! It\'s a way to honor your nation — it\'s a symbol.', NULL, '4', 0, '2025-04-09 10:28:41'),
(77, 15, 2, 'How are greeting elders and cleaning the playground alike?', 'They are both fun', 'They are both loud', 'They both show respect', 'They both take a long time', NULL, '❌ Not always fun. Think of the meaning behind them.', '❌ Zara is polite, not noisy.', '✅ Yes! One is for people, one is for places — both show care.', '❌ Not really. It\'s not about time — it\'s about meaning.', NULL, '3', 0, '2025-04-09 10:28:41'),
(78, 15, 2, 'What might happen if no one respects public property?', 'Everyone gets rich', 'The community becomes dirty and broken', 'Zara will be happy', 'Everyone claps and sings', NULL, '❌ That doesn\'t make sense. Think of what happens when things are not cared for.', '✅ Yes! Without respect, things fall apart.', '❌ No way. Zara wants her village clean and safe.', '❌ That\'s not related. Clapping doesn\'t fix broken places.', NULL, '2', 0, '2025-04-09 10:28:41'),
(79, 15, 2, 'What is one difference between respecting people and things?', 'People have feelings, things do not', 'Things are more important', 'You don\'t need to care for people', 'You can throw people away', NULL, '✅ Correct! That\'s why we are extra kind to people.', '❌ Not true. People matter most.', '❌ Oh no! Zara cares deeply about others.', '❌ That\'s hurtful and wrong. Zara would never do that.', NULL, '1', 0, '2025-04-09 10:28:41'),
(80, 15, 3, 'Zara sees her friend disrespecting a teacher. What is the best thing Zara can do?', 'Join her friend and laugh', 'Tell the teacher right away in anger', 'Talk to her friend kindly about it', 'Ignore it completely', NULL, '❌ That makes things worse. Zara values respect.', '❌ That may upset others. Zara uses calm and respect.', '✅ Yes! Zara can help her friend change by speaking kindly.', '❌ Doing nothing won’t solve the problem.', NULL, '3', 0, '2025-04-09 10:28:41'),
(81, 15, 3, 'Create a rule for your school that helps everyone show respect.', 'Always shout when you see a friend', 'Clean up only if someone is watching', 'Help others and use kind words every day', 'Use things and never return them', NULL, '❌ That’s noisy, not respectful.', '❌ That’s not true respect. It should come from the heart.', '✅ Perfect! Kindness and helpfulness create a respectful school.', '❌ That’s selfish. Zara always returns things she borrows.', NULL, '3', 0, '2025-04-09 10:28:41'),
(82, 15, 3, 'Zara wants to teach her little brother about respect. What should she do?', 'Yell at him when he’s wrong', 'Ignore him when he asks questions', 'Explain things with love and show good examples', 'Hide when he comes near', NULL, '❌ Yelling is not teaching. Respect is gentle.', '❌ That’s not kind. Zara always listens.', '✅ Yes! Teaching with love helps others learn better.', '❌ That’s not helpful. Zara wants to be a good role model.', NULL, '3', 0, '2025-04-09 10:28:41'),
(83, 15, 3, 'Why is it important to respect people who are different from us?', 'Because they are scary', 'Because everyone deserves kindness', 'So they don’t hurt us', 'So we can be better than them', NULL, '❌ That’s fear, not respect.', '✅ Exactly! Differences make us special — everyone deserves kindness.', '❌ That’s not the reason. Zara respects because it’s right, not out of fear.', '❌ That’s unkind. Respect means equality, not superiority.', NULL, '2', 0, '2025-04-09 10:28:41'),
(84, 15, 3, 'You are asked to design a “Respect Day” at school. What activity would be best?', 'Ignore others all day', 'Make a poster showing kind acts', 'Shout at classmates', 'Break things in class', NULL, '❌ That goes against everything we’ve learned.', '✅ Yes! Art and messages can spread kindness.', '❌ That’s the opposite of respect. Zara uses kind words.', '❌ No way. Respect Day should build, not break.', NULL, '2', 0, '2025-04-09 10:28:41'),
(85, 3, 1, 'What was the name of the main character in the story?', 'Chika', 'Seyi', 'Captain Tobi', 'Mummy', NULL, '❌ Chika was his friend. Hint: The one who spoke up for fairness is the main focus of the story.', '✅ Hint: He\'s the one who showed loyalty and had to make a hard decision.', '❌ He\'s the leader Seyi spoke to. Hint: Leaders play key roles but aren\'t always the main character.', '❌ She appears briefly at the end. Hint: Think about who the story follows from start to finish.', NULL, '2', 0, '2025-04-16 10:23:52'),
(86, 3, 1, 'What made Seyi speak up during the football practice?', 'He wanted to play goalie', 'He thought Chika was cheating', 'He was upset he didn\'t score', 'He noticed Chika was being\r\nleft out', NULL, '❌ That was never mentioned. Hint: His action wasn\'t about his own position.', '❌ That would show disloyalty. Hint: He was defending Chika, not accusing him.', '❌ His focus wasn\'t on himself. Hint: He was concerned for someone else.', '✅ Hint: His action came from noticing something unfair happening to his friend.', NULL, '4', 0, '2025-04-16 10:23:52'),
(87, 3, 1, 'Which action showed Seyi\'s loyalty in the story?', 'Scoring the winning goal', 'Standing up for his friend, Chika', 'Arguing with the referee', 'Quitting the team', NULL, '❌ He didn\'t score. Hint: Loyalty is about relationships, not achievements.', '✅ Hint: He defended someone who couldn\'t speak for himself.', '❌ No referee was involved. Hint: Think about calm, respectful choices.', '❌ He stayed and helped the team improve. Hint: Loyalty often means staying and helping.', NULL, '2', 0, '2025-04-16 10:23:52'),
(88, 3, 1, 'What was the team captain\'s response to Seyi\'s concern?', 'He listened and included Chika', 'He laughed at Seyi', 'He ignored him', 'He punished Chika', NULL, '✅ Hint: A good leader responds to respectful concerns.', '❌ That didn\'t happen. Hint: The captain respected Seyi\'s courage.', '❌ The story showed a change. Hint: Something positive happened after the talk.', '❌ No one was punished. Hint: The outcome helped Chika, not hurt him.', NULL, '1', 0, '2025-04-16 10:23:52'),
(89, 3, 1, 'How did Seyi feel at the end of the story?', 'Angry that he didn\'t win', 'Proud to have done the right thing', 'Scared of losing his team', 'Sad that Chika didn\'t\r\nscore', NULL, '❌ Winning wasn\'t his goal. Hint: He felt satisfied for a moral reason.', '✅ Hint: Inner peace often follows doing something brave and kind.', '❌ The team accepted him. Hint: Loyalty strengthened relationships.', '❌ That wasn\'t mentioned. Hint: His joy came from fairness, not goals.', NULL, '2', 0, '2025-04-16 10:23:52'),
(90, 3, 1, 'Which word best describes the theme of the story?', 'Jealousy', 'Loyalty', 'Strength', 'Competition', NULL, '❌ No one was envious. Hint: Think about what motivated Seyi\'s actions.', '✅ Hint: The whole story centers around sticking by someone.', '❌ Physical strength wasn\'t the focus. Hint: Emotional and moral values were emphasized.', '❌ It wasn\'t about winning. Hint: Unity, not rivalry, was the key.', NULL, '2', 0, '2025-04-16 10:23:52'),
(91, 3, 1, 'What is the best definition of \'loyalty\'?', 'Obeying every instruction', 'Helping only friends', 'Support and faithfulness to someone or something', 'Winning at all\r\ncosts', NULL, '❌ That\'s obedience. Hint: Loyalty involves choice and heart.', '❌ Loyalty can extend beyond friendships. Hint: It\'s broader than who you know.', '✅ Hint: Loyalty means standing by someone consistently.', '❌ That\'s ambition. Hint: Loyalty values people more than prizes.', NULL, '3', 0, '2025-04-16 10:23:52'),
(92, 3, 1, 'Why is it important to show loyalty in a team?', 'To win trophies', 'To build trust and unity', 'To be praised', 'To play every position', NULL, '❌ That\'s a result, not a reason. Hint: Think long-term team strength.', '✅ Hint: Teams work better when members care about each other.', '❌ Loyalty isn\'t about attention. Hint: It\'s about inner values, not rewards.', '❌ Not related. Hint: Loyalty isn\'t about roles, but relationships.', NULL, '2', 0, '2025-04-16 10:23:52'),
(93, 3, 2, 'If you saw a classmate being left out during group work, what would be the most loyal thing to do?', 'Speak up and invite them in', 'Let them be alone', 'Tell them to work harder', 'Pretend not to notice', NULL, '✅ Hint: Loyalty means taking action when someone is being ignored.', '❌ That shows indifference. Hint: Loyalty notices and responds.', '❌ That puts blame on them. Hint: Ask what they need, not what they lack.', '❌ That\'s passive. Hint: Being loyal means stepping up.', NULL, '1', 0, '2025-04-16 10:23:52'),
(94, 3, 2, 'What did Seyi\'s conversation with the captain teach us about leadership?', 'Captains always know best', 'Good leaders listen and make changes', 'Leaders should ignore complaints', 'Only strong\r\nplayers deserve attention', NULL, '❌ The captain needed feedback. Hint: Even leaders can learn from others.', '✅ Hint: Leadership includes openness to improvement.', '❌ That leads to injustice. Hint: Listening builds trust.', '❌ Everyone matters in a team. Hint: Inclusion is key.', NULL, '2', 0, '2025-04-16 10:23:52'),
(95, 3, 2, 'How is loyalty connected to fairness?', 'Loyalty is more important than fairness', 'Loyalty often leads to fair actions for everyone', 'Fairness is only for\r\nleaders', 'They are not related', NULL, '❌ They support each other. Hint: Think about their connection, not ranking.', '✅ Hint: Loyalty helps challenge unfairness.', '❌ It\'s for everyone. Hint: Fairness starts with individuals.', '❌ The story proves they are. Hint: Seyi was loyal and fair.', NULL, '2', 0, '2025-04-16 10:23:52'),
(96, 3, 2, 'Which of these is an example of disloyalty?', 'Standing up for a friend', 'Mocking someone when they fail', 'Apologizing for a mistake', 'Sharing your lunch', NULL, '❌ That\'s loyalty. Hint: Think about betrayal or ridicule.', '✅ Hint: Loyalty means lifting others up, not tearing them down.', '❌ That\'s accountability. Hint: Apologies are signs of care.', '❌ That\'s a kind act. Hint: Look for an action that hurts someone.', NULL, '2', 0, '2025-04-16 10:23:52'),
(97, 3, 2, 'How might the story have changed if Seyi had stayed silent?', 'Chika may have continued being excluded', 'Seyi would have scored a goal', 'The captain would have noticed', 'Chika\r\nwould lead the team', NULL, '✅ Hint: Change came only after someone spoke up.', '❌ That\'s unlikely and not the focus. Hint: Story impact, not sports score.', '❌ He didn\'t notice until told. Hint: Leaders need input sometimes.', '❌ Nothing suggested that. Hint: Think about cause and effect.', NULL, '1', 0, '2025-04-16 10:23:52'),
(98, 3, 2, 'Imagine you\'re in Seyi\'s shoes. What\'s the best action if your best friend is ignored in class?', 'Report them to the teacher', 'Ignore it—it\'s not your problem', 'Laugh with others', 'Talk to the class or teacher\r\nrespectfully', NULL, '❌ That sounds like blame. Hint: Focus on inclusion, not punishment.', '❌ That lacks empathy. Hint: Think about standing by others.', '❌ That adds harm. Hint: Loyalty never mocks.', '✅ Hint: Use your voice for someone else\'s good.', NULL, '4', 0, '2025-04-16 10:23:52'),
(99, 3, 2, 'Why did Seyi not care that he didn\'t score any goals?', 'He was not good at football', 'He felt that helping Chika mattered more', 'The coach praised him anyway', 'He was too\r\ntired', NULL, '❌ There\'s no evidence for that. Hint: Motivation over ability.', '✅ Hint: Values before personal success.', '❌ That wasn\'t mentioned. Hint: Inner pride, not outer reward.', '❌ Fatigue wasn\'t the issue. Hint: Emotional choice, not physical.', NULL, '2', 0, '2025-04-16 10:23:52'),
(100, 3, 2, 'What caused the turning point in the story?', 'Seyi spoke to the captain about fairness', 'Chika finally scored a goal', 'The coach changed the team', 'The game was\r\ncancelled', NULL, '✅ Hint: This was the moment of change.', '❌ That wasn\'t in the story. Hint: Focus on the moment before things improved.', '❌ The coach wasn\'t involved. Hint: Peer action led to change.', '❌ It continued. Hint: Think about what changed people, not the event.', NULL, '1', 0, '2025-04-16 10:23:52'),
(101, 3, 3, 'Was it easy or hard for Seyi to make his decision? Explain why.', 'Easy—he didn\'t care about football', 'Hard—he risked losing his place or praise', 'Easy—everyone agreed with him', 'Hard—because he was angry', NULL, '❌ He clearly cared. Hint: Sacrificing comfort isn\'t easy.', '✅ Hint: Doing the right thing isn\'t always simple.', '❌ He wasn\'t sure others would agree. Hint: He stood out, not with the crowd.', '❌ His reason wasn\'t anger. Hint: He was calm and thoughtful.', NULL, '2', 0, '2025-04-16 10:23:52'),
(102, 3, 3, 'What lesson would you write at the end of this story if you were the author?', 'Win at all costs', 'A true winner is someone who cares about others', 'Don\'t talk to captains', 'Play alone if others\r\nignore you', NULL, '❌ That\'s the opposite message. Hint: The story values kindness over victory.', '✅ Hint: He didn\'t win, but he succeeded morally.', '❌ He had a good talk! Hint: Speaking respectfully brings change.', '❌ That would isolate. Hint: Inclusion is better than withdrawal.', NULL, '2', 0, '2025-04-16 10:23:52'),
(103, 3, 3, 'How can schools encourage loyalty among classmates?', 'Punish disloyalty', 'Ignore group behavior', 'Teach teamwork and model respect', 'Separate friends', NULL, '❌ That teaches fear, not values. Hint: Positive models work better than fear.', '❌ Behavior shapes the culture. Hint: Don\'t overlook how students treat each other.', '✅ Hint: Teachers must lead by example.', '❌ That discourages bonds. Hint: Friendship and loyalty often grow together.', NULL, '3', 0, '2025-04-16 10:23:52'),
(104, 3, 3, 'Seyi and Chika are now asked to speak to their school about friendship. What should they say?', 'Be strong and ignore unfairness', 'Speak kindly and stand up for others.', 'Only help those who help you.', 'Always try\r\nto win.', NULL, '❌ That keeps problems silent. Hint: Speaking up helps.', '✅ Hint: That\'s the message of the whole story.', '❌ Loyalty isn\'t selfish. Hint: Help others even before they help you.', '❌ That’s not the story’s point. Hint: Teamwork over competition.', NULL, '2', 0, '2025-04-16 10:23:52'),
(105, 12, 1, 'What natural feature provided water for Ebitimi\'s village?', 'A deep well', 'A large lake', 'A wide river', 'A small spring', NULL, '❌ This wasn\'t the source mentioned.', '❌ Think of something that flows.', '✅ The village was near a wide river.', '❌ The source was larger than a spring.', NULL, '3', 0, '2025-04-16 10:30:18'),
(106, 12, 1, 'What materials did Ebitimi\'s village use to build homes?', 'Bricks and cement', 'Glass and steel', 'Wood and nails', 'Bamboo and thatch', NULL, '❌ Those are modern materials.', '❌ Not used in rural settings like Ebitimi\'s.', '❌ Not quite traditional enough.', '✅ These are local, natural materials.', NULL, '4', 0, '2025-04-16 10:30:18'),
(107, 12, 1, 'What is the meaning of the word pollution?', 'Cleaning the environment', 'Using natural resources wisely', 'Making the environment dirty or harmful', 'Building new houses', NULL, '❌ That\'s the opposite.', '❌ That describes sustainability.', '✅ Pollution harms nature.', '❌ Not related.', NULL, '3', 0, '2025-04-16 10:30:18'),
(108, 12, 1, 'Why did the crops rot when the rains were too heavy?', 'The sun was too hot', 'The soil became too dry', 'The soil became too wet', 'The crops were not watered', NULL, '❌ That wasn\'t the problem.', '❌ Think of water, not dryness.', '✅ Too much water caused rotting.', '❌ It rained too much, not too little.', NULL, '3', 0, '2025-04-16 10:30:18'),
(109, 12, 1, 'What lesson did Ebitimi learn from the clean-up day?', 'That playing by the river is fun', 'That the environment does not affect people', 'That caring for the environment brings pride and unity', 'That children cannot help in community work', NULL, '❌ That\'s not what she learned.', '❌ It actually does.', '✅ The clean-up brought people together.', '❌ Children played a big part.', NULL, '3', 0, '2025-04-16 10:30:18'),
(110, 12, 1, 'Why did Ebitimi organize a clean-up day?', 'To sell trash for money', 'To impress the village council', 'To keep the riverbank clean', 'To build a new playground', NULL, '❌ That was not the purpose.', '❌ It was for a bigger reason.', '✅ That was her goal.', '❌ Not related to the river.', NULL, '3', 0, '2025-04-16 10:30:18'),
(111, 12, 1, 'What is the meaning of sustainability?', 'Throwing away waste', 'Cleaning the house daily', 'Continuing something over a long time', 'Eating natural food', NULL, '❌ That\'s about disposal.', '❌ Not long-term focused.', '✅ Sustainability is about lasting actions.', '❌ That\'s a healthy habit but not the definition.', NULL, '3', 0, '2025-04-16 10:30:18'),
(112, 12, 1, 'Which of these is NOT an effect of keeping the environment clean?', 'Reducing pollution', 'Feeling proud', 'Getting sick', 'Helping the community', NULL, '❌ That is a benefit.', '❌ People feel proud of clean places.', '✅ Clean environments reduce sickness.', '❌ That\'s a positive result.', NULL, '3', 0, '2025-04-16 10:30:18'),
(113, 12, 2, 'If the villagers continue to throw litter into the river, what might happen?', 'The river will grow longer', 'The water will become cleaner', 'The river may become polluted and unsafe', 'The fish will become bigger', NULL, '❌ Litter doesn\'t affect river length.', '❌ Trash makes water dirty.', '✅ Litter pollutes water.', '❌ Pollution harms fish, not helps.', NULL, '3', 0, '2025-04-16 10:30:18'),
(114, 12, 2, 'What can you do if someone refuses to join a clean-up activity?', 'Yell at them to participate', 'Report them to the police', 'Explain kindly why the clean-up is important', 'Ignore them completely', NULL, '❌ That could make things worse.', '❌ This isn\'t a police matter.', '✅ Kindness helps change minds.', '❌ That misses a chance to educate.', NULL, '3', 0, '2025-04-16 10:30:18'),
(115, 12, 2, 'Which of the following is an action that contributes positively to the environment?', 'Burning plastic waste', 'Littering after a party', 'Planting trees in the community', 'Using more paper unnecessarily', NULL, '❌ That causes air pollution.', '❌ That dirties the surroundings.', '✅ Trees help the environment.', '❌ That leads to waste.', NULL, '3', 0, '2025-04-16 10:30:18'),
(116, 12, 2, 'How does the environment affect how people live?', 'It gives them free things', 'It doesn\'t really matter', 'It shapes their way of life like farming and building', 'It makes them live alone', NULL, '❌ That\'s not how the environment works.', '❌ It matters a lot.', '✅ Environment influences lifestyle.', '❌ Not related.', NULL, '3', 0, '2025-04-16 10:30:18'),
(117, 12, 2, 'What was the purpose of setting up recycling bins in Ebitimi\'s village?', 'To store food', 'To save money', 'To sort and reuse waste properly', 'To decorate the village', NULL, '❌ That\'s not the purpose of recycling bins.', '❌ That wasn\'t the main goal.', '✅ Recycling is about managing waste.', '❌ Though colorful, bins are functional.', NULL, '3', 0, '2025-04-16 10:30:18'),
(118, 12, 2, 'What problem did Ebitimi solve with the help of the village council?', 'Building a new river', 'Cleaning the river once', 'Creating a monthly clean-up and awareness plan', 'Organizing a food festival', NULL, '❌ You can\'t build a river.', '❌ She worked on a lasting solution.', '✅ It became a regular activity.', '❌ That was not the issue she tackled.', NULL, '3', 0, '2025-04-16 10:30:18'),
(119, 12, 2, 'If a child sees another child throwing litter on the ground, what is the best thing to do?', 'Laugh and walk away', 'Tell the teacher or explain kindly', 'Join them', 'Push them', NULL, '❌ That doesn\'t help.', '✅ It\'s helpful and respectful.', '❌ That makes the problem worse.', '❌ Violence is never the right choice.', NULL, '2', 0, '2025-04-16 10:30:18'),
(120, 12, 2, 'How are the villagers\' building practices connected to the environment?', 'They copy city houses', 'They buy materials from far away', 'They use local materials that suit the climate', 'They build houses using machines', NULL, '❌ They don\'t follow city designs.', '❌ They use what\'s nearby.', '✅ Their homes match the environment.', '❌ That\'s not how village homes are built.', NULL, '3', 0, '2025-04-16 10:30:18'),
(121, 12, 3, 'Why do you think some villagers refused to join the clean-up?', 'They did not have time', 'They hated the river', 'They did not understand the importance', 'They wanted to go fishing', NULL, '❌ That may be true for some, but it\'s not the main reason.', '❌ Most villagers relied on the river.', '✅ Lack of awareness can lead to inaction.', '❌ That\'s not a likely cause for refusal.', NULL, '3', 0, '2025-04-16 10:30:18'),
(122, 12, 3, 'What could happen in the future if people like Ebitimi don\'t take action to protect the environment?', 'Rivers will stay clean', 'Communities will be healthier', 'Pollution may increase, harming people and animals', 'The government will clean everything', NULL, '❌ Rivers get dirty without care.', '❌ Pollution harms health.', '✅ Ignoring pollution allows it to grow.', '❌ Everyone has a role to play.', NULL, '3', 0, '2025-04-16 10:30:18'),
(123, 12, 3, 'Imagine your school has a dirty playground. What is the best first step to solve the problem?', 'Wait for the teachers', 'Organize a clean-up with classmates', 'Complain to the principal', 'Leave it alone', NULL, '❌ You can also take initiative.', '✅ Working together is a great first step.', '❌ Complaining isn\'t action.', '❌ Ignoring it makes it worse.', NULL, '2', 0, '2025-04-16 10:30:18'),
(124, 12, 3, 'What message would you write on a sign to encourage environmental care?', 'Don\'t play here!', 'Litter makes the Earth sad—keep it clean!', 'Only adults clean here!', 'We like trash!', NULL, '❌ This doesn\'t teach anything about caring for the environment.', '✅ It\'s friendly, creative, and sends a clear message.', '❌ Children can help too.', '❌ This sends the wrong message.', NULL, '2', 0, '2025-04-16 10:30:18');
INSERT INTO `questions` (`question_id`, `lesson_id`, `type`, `question`, `option1`, `option2`, `option3`, `option4`, `option5`, `feedback1`, `feedback2`, `feedback3`, `feedback4`, `feedback5`, `answer`, `marks`, `createdate`) VALUES
(125, 12, 3, 'You want to start an environmental club in your school. What activities could your club organize?', 'Water fights', 'Watching TV', 'Monthly clean-ups, planting trees, and awareness campaigns', 'Selling junk food', NULL, '❌ That\'s just play, not environmental action.', '❌ Not helpful for the environment.', '✅ These actions care for the environment.', '❌ That doesn\'t help with health or the environment.', NULL, '3', 0, '2025-04-16 10:30:18');

-- ============================================================================
-- Migration: Import legacy `questions` into new `test_questions` schema safely
-- This block only INSERTS; it will not modify or delete existing rows.
-- Requirements:
--   - Table `lessons` exists and is populated (lesson_id, subject_id, class_id)
--   - Table `tests` exists with primary key `id`
--   - New table `test_questions` will be created if missing (see DDL below)
--
-- If your `tests` table already has one row per lesson (via tests.lesson_id),
-- you may skip the step that inserts tests from lessons.
-- ============================================================================

-- 0) Create new table if it does not exist (adjust if you already created it)
CREATE TABLE IF NOT EXISTS test_questions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  test_id INT NOT NULL,
  question_text TEXT NOT NULL,
  question_type ENUM('multiple_choice', 'true_false', 'short_answer', 'essay') NOT NULL,
  marks INT NOT NULL,
  options JSON,
  correct_answer TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE
);

START TRANSACTION;

-- 1) Ensure a test exists for every lesson (insert only when missing)
--    This matches your existing tests schema (no lesson_id column).
--    It picks any available teacher as owner; adjust if you want a specific teacher.
INSERT INTO tests (
  title, description, class_id, subject_id, teacher_id,
  test_type, total_marks, duration_minutes,
  scheduled_date, start_time, end_time, is_active
)
SELECT
  CONCAT(l.title, ' [Imported]') AS title,
  '' AS description,
  l.class_id,
  l.subject_id,
  COALESCE((SELECT u.id FROM users u WHERE u.role='teacher' ORDER BY u.id LIMIT 1), (SELECT u2.id FROM users u2 WHERE u2.role='superadmin' ORDER BY u2.id LIMIT 1)) AS teacher_id,
  'quiz' AS test_type,
  100 AS total_marks,
  30 AS duration_minutes,
  CURDATE() AS scheduled_date,
  '09:00:00' AS start_time,
  '10:00:00' AS end_time,
  1 AS is_active
FROM lessons l
WHERE NOT EXISTS (
  SELECT 1 FROM tests t
  WHERE t.title = CONCAT(l.title, ' [Imported]')
    AND t.class_id = l.class_id
    AND t.subject_id = l.subject_id
);

-- 2) Import questions into test_questions, avoiding duplicates per (test, text)
INSERT INTO test_questions (
  test_id,
  question_text,
  question_type,
  marks,
  options,
  correct_answer,
  created_at
)
SELECT
  t.id AS test_id,
  q.question AS question_text,
  CASE
    WHEN COALESCE(NULLIF(TRIM(LOWER(q.option3)),'') , '') = ''
     AND COALESCE(NULLIF(TRIM(LOWER(q.option4)),'') , '') = ''
     AND COALESCE(NULLIF(TRIM(LOWER(q.option5)),'') , '') = ''
     AND LOWER(TRIM(q.option1)) IN ('true','false')
     AND LOWER(TRIM(q.option2)) IN ('true','false')
    THEN 'true_false'
    ELSE 'multiple_choice'
  END AS question_type,
  CAST(q.marks AS SIGNED) AS marks,
  JSON_MERGE_PRESERVE(
    IF(q.option1 IS NOT NULL AND q.option1 <> '', JSON_ARRAY(q.option1), JSON_ARRAY()),
    IF(q.option2 IS NOT NULL AND q.option2 <> '', JSON_ARRAY(q.option2), JSON_ARRAY()),
    IF(q.option3 IS NOT NULL AND q.option3 <> '', JSON_ARRAY(q.option3), JSON_ARRAY()),
    IF(q.option4 IS NOT NULL AND q.option4 <> '', JSON_ARRAY(q.option4), JSON_ARRAY()),
    IF(q.option5 IS NOT NULL AND q.option5 <> '', JSON_ARRAY(q.option5), JSON_ARRAY())
  ) AS options,
  NULLIF(TRIM(q.answer), '') AS correct_answer,
  q.createdate AS created_at
FROM questions q
JOIN lessons l ON l.lesson_id = q.lesson_id
JOIN tests t   ON t.title = CONCAT(l.title, ' [Imported]')
              AND t.class_id = l.class_id
              AND t.subject_id = l.subject_id
WHERE NOT EXISTS (
  SELECT 1 FROM test_questions tq
  WHERE tq.test_id = t.id
    AND tq.question_text = q.question
);

COMMIT;

-- To revert this import only (if needed), you can remove the inserted test rows
-- that have the "[Imported]" suffix and their cascading questions:
-- DELETE t FROM tests t WHERE t.title LIKE '%[Imported]';
-- This relies on ON DELETE CASCADE to remove related test_questions.

